### PR TITLE
[FIX] nortenas: Deleted inherited check_negative_qty method. vx#40065

### PR DESCRIPTION
**Pull request by deivislaya**
The adjustment in the method for negative quants has been applied at
https://github.com/odoo/odoo/commit/f7168311f4333f7fc684e00e1c1c284981718335

### CODE REVIEW

**Comment by deivislaya** [comment]
@ljpachec 

This MR is ready for review 

Regards!

**Comment by hugho-ad** [comment]
rebase this please

**Comment by deivislaya** [comment]
@ljpachec @hugho-ad 

Rebase  ready, please merge

Regards!

**Comment by hugho-ad** [comment]
@deivislaya 

please rebase

**Comment by hugho-ad** [comment]
@ljpachec 

We'll need to check  this, because  531 files were changed when updating stock-logistics-workflow repo

this is needed because we are removing a patch on vauxoo/norteñas that was already merged on Oca module stock_no_negative

**Comment by deivislaya** [comment]
@hugho-ad  @ljpachec 

The change had been applied too in odoo 

https://github.com/odoo/odoo/commit/f7168311f4333f7fc684e00e1c1c284981718335

No need to update the repo  Vauxoo / stock-logistics-workflow

Regards!

**Comment by hugho-ad** [comment]
@deivislaya @ljpachec 

If norteñas always do the unpack it's ok for me

The reason that would like to keep it it's that de merge_quants it's always called because the constraint, not only on unpacking process

**Comment by deivislaya** [comment]
@ljpachec @hugho-ad 

Rebase ready 

Regards!

**Pull request merged**
