### PR TITLE
[REF] Dependency helpdesk mexico vx#11960

### PR DESCRIPTION
**Pull request by oskr1087**
New helpdesk dependencies in the norteno app and mexico repository in oca dependencies

related to: https://git.vauxoo.com/vauxoo/nortenas/-/merge_requests/68

### CODE REVIEW

**Comment by hugho-ad** [comment]
missing submodule to vauxoo-mexico

**Comment by oskr1087** [comment]
@hugho-ad 

Please review this PR

Regards

**Review by hugho-ad — APPROVED** [review]

**Comment by hugho-ad** [comment]
LGTM :+1: 

@ljpachec 
ready to go

**Comment by hugho-ad** [comment]
@ljpachec 

Abort, staging is read
need to check

**Pull request merged**
